### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by hairygodfather** [adwisatya/TwitterSpaces2Text#1]
Hello,

I am getting this error when trying to install on
C:\Python>py --version
Python 3.10.5
/Thanks in advance!
--
C:\Users\slimjim>pip install TwitterSpaces2Text
Collecting TwitterSpaces2Text
  Using cached TwitterSpaces2Text-0.1.tar.gz (2.6 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [12 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\slimjim\AppData\Local\Temp\pip-install-t7obqjaz\twitterspaces2text_a152f74be907404ea36a7491c5df9dae\setup.py", line 3, in <module>
          subprocess.run(["pandoc","--from=markdown","--to=rst","--output=README","README.md"])
        File "C:\Python\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Python\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Python\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

(i was able to install another github also stored in same site-packages directory with success
C:\Users\slimjim>pip install pyautogui
...
Successfully installed PyTweening-1.0.4 mouseinfo-0.1.3 pyautogui-0.9.53 pygetwindow-0.0.9 pymsgbox-1.0.9 pyperclip-1.8.2 pyrect-0.2.0 pyscreeze-0.1.28)

**Comment by adwisatya** [comment]
Hi @hairygodfather , what version your Python is?

This lib need python3 and pip3 for installation

**Comment by hairygodfather** [comment]
Hello,

Thanks for the questions.
Here is the output
C:\Users\slimjim>pip3 --version
pip 22.1.2 from C:\Python\lib\site-packages\pip (python 3.10)

C:\Users\slimjim>py --version
Python 3.10.5

what do you think?

Thanks again

**Comment by adwisatya** [comment]
I got it now. This was not related to python version but pandac not available in Windows. I will make fix for this.

**Comment by adwisatya** [comment]
Just pushed v0.1.1 to fix this issue. Kindly try to install again using pip @hairygodfather

**Comment by hairygodfather** [comment]
Thanks. Install working now. Issued resolved.
